cc_binary(
    name = "hello_world",
    visibility = None,
    srcs = ["hello_world.cc"],
    deps = [
      "@com_google_mediapipe//mediapipe/calculators/core:pass_through_calculator",
      "@com_google_mediapipe//mediapipe/framework:calculator_framework",
      "@com_google_mediapipe//mediapipe/framework/port:logging",
      "@com_google_mediapipe//mediapipe/framework/port:parse_text_proto",
      "@com_google_mediapipe//mediapipe/framework/port:status",
    ],
)
